## **Week 3 Applied Session: Regular Expression**

In the lecture, you have learnt how to use regular expressions. To quickly review some regular expression syntax:


* <font color="red">[0-9]</font> Matches a single digit
* <font color="red">[a-z0-9]</font> Matches a single character that must be a lower case letter or a digit.
* <font color="red">[A-Za-z]</font> Matches a single character that much be a upper/lower case letter
* <font color="red">\d</font> Matches any decimal digit; equivalent to the set [0-9].
* <font color="red">\D</font> Matches characters that are not digits, which is equivalent to [^0-9] or [^\d].
* <font color="red">\w</font> Matches any alphanumeric character, which is equivalent to [a-zA-Z0-9].
* <font color="red">\W</font> Matches any non-alphanumeric character; which is equivalent to [^a-zA-Z0-9] or [^\w].
* <font color="red">\s</font> Matches any whitespace character; which is equivalent to [\t\n\r\f\v], where \t indicates taps, \n  line feeds, \r carriage returns, \f form feeds and \v vertical tabs.
* <font color="red">\S:</font> Matches any non-whitespace character; which is equivalent to  [^ \t\n\r\f\v].
* <font color="red">ˆ</font> Matches the start of the line.
* <font color="red">$</font> Matches the end of the line.
* <font color="red">.</font> Matches any character (a wildcard).
* <font color="red">*</font> Matches when the preceding character occurs zero or more times
* <font color="red">?</font> Matches when the preceding character occurs zero or one times
* <font color="red">+</font> Matches when the preceding character occurs one or more times

More information can be found here :
https://docs.python.org/3/library/re.html
* * *

Let's get ready!!!

In [31]:
import sys
print (sys.version_info)

sys.version_info(major=3, minor=13, micro=12, releaselevel='final', serial=0)

Libraries needed are:

In [32]:
import re # library for regular expression
import pandas as pd
pd.__version__

'3.0.1'

### **1. Backslash**

**What is `\`?**

`\`, backslash or escape-character, is used to indicate special forms or to allow special characters to be used without invoking their special meaning.

**How about `r""` ? When to use it?**

`""` is Python's string literal prefix notation, which has nothing to do with regular expression.  By using `r""` or `r''`, Python will not handle special characters in any special way, in another word, it treated the contents as raw string. For example, `"\t"` represents
a two-character string containing `'\'` and `'t'`, whereas `"\t"` represents tab.

Sometimes you can use them interchangeably,

In [33]:
str1 = re.findall('\\t', "Please find \t")
print (str1)

str2 = re.findall(r'\\t', "Please find \\t")
print (str2)

['\t']
['\\t']

In [34]:
print('\\t')

\t

Sometimes not!

In [35]:
str3 = re.findall('\\\t', "Please find \t")
print (str3)
print('\\t')
print("Please find \\t")

['\t']
\t
Please find \t

In [36]:
r'\t'

'\\t'

In [37]:
s = 't\\t\tt'
print(s)

t\t	t

In [38]:
str1=re.match(r"\W(.)\1\W", " ff ")
print (str1)

str2=re.match("\W(.)\1\W", " ff ")
print (str2)

str3=re.match("\\W(.)\\1\\W", " ff ")
print (str3)

<re.Match object; span=(0, 4), match=' ff '>
None
<re.Match object; span=(0, 4), match=' ff '>

<>:4: SyntaxWarning: invalid escape sequence '\W'
<>:4: SyntaxWarning: invalid escape sequence '\W'
/var/folders/6s/bb6mgp0x50q3fjlqfsfpffjm0000gn/T/ipykernel_62980/2893283065.py:4: SyntaxWarning: invalid escape sequence '\W'
  str2=re.match("\W(.)\1\W", " ff ")

`"\W(.)\1\W"` doesn't match? What is the difference?

In [39]:
str4="\W(.)\1\W"
print (str4)
str4

\W(.)\W

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
/var/folders/6s/bb6mgp0x50q3fjlqfsfpffjm0000gn/T/ipykernel_62980/756452606.py:1: SyntaxWarning: invalid escape sequence '\W'
  str4="\W(.)\1\W"

'\\W(.)\x01\\W'

In [40]:
str4=r"\W(.)\1\W"
print (str4)
str4

\W(.)\1\W

'\\W(.)\\1\\W'

Now you might be able to guess, what `"\W(.)\1\W"` will match.

In [41]:
str2=re.match("\W(.)\1\W", " f\x01 ")
print (str2)

<re.Match object; span=(0, 4), match=' f\x01 '>

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
/var/folders/6s/bb6mgp0x50q3fjlqfsfpffjm0000gn/T/ipykernel_62980/2062020237.py:1: SyntaxWarning: invalid escape sequence '\W'
  str2=re.match("\W(.)\1\W", " f\x01 ")

It matches with non-word + any one character  + "\x01" + non-word.

**Note**: always fist validate your regular expression, then test with Python

\* is ??  <br>
\* is a wildcard similar with ? and +  <br>
\* matches 0+ <br>
? matches 0-1 <br>
\+ matches 1+ <br>

In [42]:
str1 = re.findall(r'.*', 'Please find all.')
print (str1)

['Please find all.', '']

In [43]:
str1 = re.findall(r'.?', 'Please find all.')
print (str1)

['P', 'l', 'e', 'a', 's', 'e', ' ', 'f', 'i', 'n', 'd', ' ', 'a', 'l', 'l', '.', '']

In [44]:
str1 = re.findall(r'.+', 'Please find all.')
print (str1)

['Please find all.']

In [45]:
str1 = re.findall(r'l+', 'Please find all')
print (str1)

['l', 'll']

## **2. Regular Expression for Dates**

Refine the regular expression for date to distinguish months with 29/30/31 days.

**Note**: assume all years are a leap year, which means every Feburary has 29 days.

In [46]:
# define a function to validate the input date
def date(pattern, m):
    if re.match(pattern, m):
        print (m + " is a date")
    else:
        print (m + " is NOT a date")

In [47]:
regex = r'''(?x)
    (?:
    # February (29 days every year)
      ([12][0-9]|0?[1-9])[/-](0?2)
    # 30-day months
      |(30|[12][0-9]|0?[1-9])[/-](0?[469]|11)
    # 31-day months
      |(3[01]|[12][0-9]|0?[1-9])[/-](0?[13578]|1[02])
    )
    # Year
    [/-]((?:[0-9]{2})?[0-9]{2})
'''

In [48]:
#date(r"((31[/-](0?[13578]|1[02]))|(30[/-](0?[469]|11))|(28[/-]02))[/-]((?:\d{2})?\d{2})", "28/02/2019")
date(regex, "28/02/2019")
date(regex, "31/04/2019")
date(regex, "29/05/2019")
date(regex, "31/06/2019")

28/02/2019 is a date
31/04/2019 is NOT a date
29/05/2019 is a date
31/06/2019 is NOT a date

We can draw the diagram to demon the logic of this regular expression:

![](https://drive.google.com/uc?export=download&id=1Wk7voq-u0iNBZ9wF-cBAjdvLowJoRaFJ)

## **3. Extract IPs, dates, and email address with regular expressions**

With following tasks we will use the mail box data ([mbox-short.txt](http://www.pythonlearn.com/code3/mbox-short.txt)) provided by the book [Python for Informatics: Exploring Information](http://www.pythonlearn.com/book.php#python-for-informatics).

In [49]:
# Colab please use this directory: '/content/drive/Shareddrives/FIT5196_S2_2025/week3/mbox-short.txt' as input directory
# If you are using a local environment, you can download the file from your shared drive and use the file path as input directory
infile = open('mbox-short.txt','r')

text = infile.read()

In [50]:
 text[:100]

'\\t\t\t\t\nFrom stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008\nReturn-Path: <postmaster@collab.sakai'

### **3.1 Find IP addresses**

We are trying to
1. find all IP addresses in the mbox-short dataset.
2. print unique IP addresses

In [51]:
str1 = re.findall(r'\b(?:\d{1,3}\.){3}\d{1,3}\b', "This is a IP address 111.23.39.99")
str1

['111.23.39.99']

![](https://drive.google.com/uc?export=download&id=1v5Os9EzlTo1sNwbMF9MTTMOZ0NpQVe9M)
From https://regexper.com/

In [52]:
str1= re.findall(r'(?:[0-9]{1,3}\.){3}[0-9]{1,3}', text)
if len(str1)>0:
    print (str1)

['141.211.14.90', '141.211.14.79', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.97', '141.211.93.149', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.25', '141.211.93.144', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.25', '141.211.14.43', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.46', '141.211.14.83', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.93', '141.211.93.142', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.46', '141.211.14.72', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.46', '141.211.93.151', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.25', '141.211.14.79', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.36', '141.211.14.84', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.97', '141.211.93.152', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.39', '141.211.14.79', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.90', '141.211.93.153', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.97', '141.211.14.84', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.25', '141.211.14.79', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.90', '141.211.14.76', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.39', '141.211.14.76', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.98', '141.211.14.83', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.92', '141.211.93.145', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.46', '141.211.93.143', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.25', '141.211.14.58', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.91', '141.211.93.142', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.91', '141.211.14.58', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.39', '141.211.93.141', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.34', '141.211.93.149', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.46', '141.211.93.145', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.91', '141.211.14.58', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200']

By running the code above, we are able to print all IP addresses.

Next can we save all unique IP address in a list? We will need to read the whole txt file in to `text`, and then apply `re.findall` function. `set()` function returns the unique values.

In [53]:
str1=re.findall(r'(?:[0-9]{1,3}\.){3}[0-9]{1,3}', text)
set(str1)

{'127.0.0.1',
 '134.68.220.122',
 '141.211.14.25',
 '141.211.14.34',
 '141.211.14.36',
 '141.211.14.39',
 '141.211.14.43',
 '141.211.14.46',
 '141.211.14.58',
 '141.211.14.72',
 '141.211.14.76',
 '141.211.14.79',
 '141.211.14.83',
 '141.211.14.84',
 '141.211.14.90',
 '141.211.14.91',
 '141.211.14.92',
 '141.211.14.93',
 '141.211.14.97',
 '141.211.14.98',
 '141.211.93.141',
 '141.211.93.142',
 '141.211.93.143',
 '141.211.93.144',
 '141.211.93.145',
 '141.211.93.149',
 '141.211.93.151',
 '141.211.93.152',
 '141.211.93.153',
 '194.35.219.182',
 '194.35.219.184',
 '8.12.11.200'}

### **3.2 Extract All date time**


In the next task, we need to extract all date time from the file. We trust that all date time are valid for now.

In [54]:
str1=re.findall(r'(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})', text)
set(str1)

{'2007-09-12 16:17:59',
 '2007-12-12 21:40:33',
 '2007-12-17 17:11:08',
 '2007-12-20 15:25:38',
 '2007-12-20 21:26:28',
 '2007-12-28 23:44:24',
 '2008-01-03 16:22:14',
 '2008-01-03 16:27:29',
 '2008-01-03 16:33:02',
 '2008-01-03 17:05:11',
 '2008-01-03 17:16:39',
 '2008-01-03 19:23:46',
 '2008-01-04 04:05:43',
 '2008-01-04 04:31:35',
 '2008-01-04 04:47:16',
 '2008-01-04 06:05:51',
 '2008-01-04 07:00:10',
 '2008-01-04 09:02:54',
 '2008-01-04 10:01:40',
 '2008-01-04 10:15:54',
 '2008-01-04 10:37:04',
 '2008-01-04 11:08:38',
 '2008-01-04 11:09:12',
 '2008-01-04 11:10:04',
 '2008-01-04 11:11:00',
 '2008-01-04 11:33:05',
 '2008-01-04 11:35:25',
 '2008-01-04 13:05:51',
 '2008-01-04 14:48:37',
 '2008-01-04 15:01:37',
 '2008-01-04 15:44:39',
 '2008-01-04 16:09:01',
 '2008-01-04 18:08:50',
 '2008-01-05 09:12:07'}

### **3.3 Extract author's email address**


There are many email addresses included in the file. We would like to extract email addresses from the Author the format is normally:

`"Author: stephen.marquard@uct.ac.za"`

Now lets see if we can use the following regular expression:

```python
r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+"
```
which was copied and pasted from http://emailregex.com/

Does it work in the task?

In [55]:
str1=re.findall(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+", text)
set(str1)

{'200801032122.m03LMFo4005148@nakamura.uits.iupui.edu',
 '200801032127.m03LRUqH005177@nakamura.uits.iupui.edu',
 '200801032133.m03LX3gG005191@nakamura.uits.iupui.edu',
 '200801032205.m03M5Ea7005273@nakamura.uits.iupui.edu',
 '200801032216.m03MGhDa005292@nakamura.uits.iupui.edu',
 '200801040023.m040NpCc005473@nakamura.uits.iupui.edu',
 '200801040905.m0495rWB006420@nakamura.uits.iupui.edu',
 '200801040932.m049W2i5006493@nakamura.uits.iupui.edu',
 '200801040947.m049lUxo006517@nakamura.uits.iupui.edu',
 '200801041106.m04B6lK3006677@nakamura.uits.iupui.edu',
 '200801041200.m04C0gfK006793@nakamura.uits.iupui.edu',
 '200801041403.m04E3psW006926@nakamura.uits.iupui.edu',
 '200801041502.m04F21Jo007031@nakamura.uits.iupui.edu',
 '200801041515.m04FFv42007050@nakamura.uits.iupui.edu',
 '200801041537.m04Fb6Ci007092@nakamura.uits.iupui.edu',
 '200801041608.m04G8d7w007184@nakamura.uits.iupui.edu',
 '200801041609.m04G9EuX007197@nakamura.uits.iupui.edu',
 '200801041610.m04GA5KP007209@nakamura.uits.iupui.edu',
 '200801041611.m04GB1Lb007221@nakamura.uits.iupui.edu',
 '200801041633.m04GX6eG007292@nakamura.uits.iupui.edu',
 '200801041635.m04GZQGZ007313@nakamura.uits.iupui.edu',
 '200801041948.m04JmdwO007705@nakamura.uits.iupui.edu',
 '200801042001.m04K1cO0007738@nakamura.uits.iupui.edu',
 '200801042044.m04Kiem3007881@nakamura.uits.iupui.edu',
 '200801042109.m04L92hb007923@nakamura.uits.iupui.edu',
 '200801042308.m04N8v6O008125@nakamura.uits.iupui.edu',
 '200801051412.m05ECIaH010327@nakamura.uits.iupui.edu',
 'antranig@caret.cam.ac.uk',
 'cwen@iupui.edu',
 'david.horwitz@uct.ac.za',
 'gopal.ramasammycook@gmail.com',
 'gsilver@umich.edu',
 'hu2@iupui.edu',
 'josrodri@iupui.edu',
 'louis@media.berkeley.edu',
 'postmaster@collab.sakaiproject.org',
 'ray@media.berkeley.edu',
 'rjlowe@iupui.edu',
 'source@collab.sakaiproject.org',
 'stephen.marquard@uct.ac.za',
 'wagnermr@iupui.edu',
 'zqian@umich.edu'}

What if I only want email address after Author ?

In [56]:
str1=re.findall(r'Author: ([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)', text)
str1

['stephen.marquard@uct.ac.za',
 'louis@media.berkeley.edu',
 'zqian@umich.edu',
 'rjlowe@iupui.edu',
 'zqian@umich.edu',
 'rjlowe@iupui.edu',
 'cwen@iupui.edu',
 'cwen@iupui.edu',
 'gsilver@umich.edu',
 'gsilver@umich.edu',
 'zqian@umich.edu',
 'gsilver@umich.edu',
 'wagnermr@iupui.edu',
 'zqian@umich.edu',
 'antranig@caret.cam.ac.uk',
 'gopal.ramasammycook@gmail.com',
 'david.horwitz@uct.ac.za',
 'david.horwitz@uct.ac.za',
 'david.horwitz@uct.ac.za',
 'david.horwitz@uct.ac.za',
 'stephen.marquard@uct.ac.za',
 'louis@media.berkeley.edu',
 'louis@media.berkeley.edu',
 'ray@media.berkeley.edu',
 'cwen@iupui.edu',
 'cwen@iupui.edu',
 'cwen@iupui.edu']

## **Task: Read and load raw data**

Last week, we load an `Air Crashes` data in Task 2. The csv file has been already preprocessed in a structured format. However, most of time, we need to work directly on the raw data.

In this task, you will load the raw data file for `Air Crashes` and use regular expressions to convert it into the appropriate structure.

In [57]:
# Colab please use the following directory in codes below
# If you are using a local environment, you can download the file from your shared drive and use the file path as input directory

# load data in target structure
aircrash = pd.read_csv('AirCrashes.csv')
aircrash.head()

,Flight,Mode,Casualties,Circumstances,Country,Crew,Date,Ground,Latitude,Location,Longitude,Notes,Passengers,Phase,Reason,Total Dead,Type
0,Aeroflot Flight 217,Ilyushin Il-62,Extremely High,Bad Visibility by Day,Russia,10,13/10/1972,0,55.755826,Moscow - Russia,37.617300,No survivors,164,APR,Accident,174,COM
1,Aeroflot Flight 3352,Tupolev Tu-154,Extremely High,Bad Visibility by Night,Russia,5,11/10/1984,4,54.966667,Omsk - Russia,73.383333,Some survivors,169,LDG,Accident,178,COM
2,Aeroflot Flight 4227,Tupolev Tu-154B-2,Extremely High,Bad Visibility by Night,Kazakhstan,10,1890-07-08,0,43.255058,Almaty - Kazakhstan,76.912628,No survivors,156,ENR,Accident,166,COM
3,Aeroflot Flight 7425,NaN,Extremely High,Bad Visibility by Night,NaN,9,10/7/1985,0,42.156667,Uchkuduk - Uzbekistan,63.555556,No survivors,191,ENR,Accident,0,COM
4,Aeroflot/Moldovia (CCCP-65816),Tupolev Tu-134A(both),Extremely High,Bad Visibility by Night,Kazakhstan,13,11/8/1979,0,48.812500,NaN,46.763611,No survivors,165,ENR,Accident,178,COM

Above is the final structure we would like to have.

Now, let's open the raw file.

In [58]:
# load raw data
df = pd.read_csv('AirCrashes_raw.csv')
df.shape

(927, 1)

In [59]:
df.head(30)

                                                   Incident American Airlines Flight 11 involving a Boeing 767-223ER in 2001
Casualties                                                                             Extremely High
Total Dead                                                                                       1692
Crew                                                                                               11
Passengers                                                                                         81
Ground                                                                                           1600
Notes                                                                                    No survivors
Type                                                                                              INH
Reason                                                                                         Attack
Location                                                                     New York - New York - US
Country                                                                                            US
Phase                                                                                             ENR
Date                                                                                       2001-09-11
Latitude                                                                                   40.7143528
Longitude                                                                                 -74.0059731
Circumstances                                                                  Good Visibility by Day
Incident United Airlines Flight 175 involving a...                                                NaN
Casualties                                                                             Extremely High
Total Dead                                                                                        965
Crew                                                                                                9
Passengers                                                                                         56
Ground                                                                                            900
Notes                                                                                    No survivors
Type                                                                                              INH
Reason                                                                                         Attack
Location                                                                     New York - New York - US
Country                                                                                           USA
Phase                                                                                             ENR
Date                                                                                       2001-09-11
Latitude                                                                                   40.7143528
Longitude                                                                                 -74.0059731