## **Week 3 Applied Session: Regular Expression**

In the lecture, you have learnt how to use regular expressions. To quickly review some regular expression syntax:


* <font color="red">[0-9]</font> Matches a single digit
* <font color="red">[a-z0-9]</font> Matches a single character that must be a lower case letter or a digit.
* <font color="red">[A-Za-z]</font> Matches a single character that much be a upper/lower case letter
* <font color="red">\d</font> Matches any decimal digit; equivalent to the set [0-9].
* <font color="red">\D</font> Matches characters that are not digits, which is equivalent to [^0-9] or [^\d].
* <font color="red">\w</font> Matches any alphanumeric character, which is equivalent to [a-zA-Z0-9].
* <font color="red">\W</font> Matches any non-alphanumeric character; which is equivalent to [^a-zA-Z0-9] or [^\w].
* <font color="red">\s</font> Matches any whitespace character; which is equivalent to [\t\n\r\f\v], where \t indicates taps, \n  line feeds, \r carriage returns, \f form feeds and \v vertical tabs.
* <font color="red">\S:</font> Matches any non-whitespace character; which is equivalent to  [^ \t\n\r\f\v].
* <font color="red">ˆ</font> Matches the start of the line.
* <font color="red">$</font> Matches the end of the line.
* <font color="red">.</font> Matches any character (a wildcard).
* <font color="red">*</font> Matches when the preceding character occurs zero or more times
* <font color="red">?</font> Matches when the preceding character occurs zero or one times
* <font color="red">+</font> Matches when the preceding character occurs one or more times

More information can be found here :
https://docs.python.org/3/library/re.html
* * *

Let's get ready!!!

In [17]:
import sys
print (sys.version_info)

sys.version_info(major=3, minor=13, micro=12, releaselevel='final', serial=0)

Libraries needed are:

In [18]:
import re # library for regular expression
import pandas as pd
pd.__version__

'3.0.1'

### **1. Backslash**

**What is `\`?**

`\`, backslash or escape-character, is used to indicate special forms or to allow special characters to be used without invoking their special meaning.

**How about `r""` ? When to use it?**

`""` is Python's string literal prefix notation, which has nothing to do with regular expression.  By using `r""` or `r''`, Python will not handle special characters in any special way, in another word, it treated the contents as raw string. For example, `"\t"` represents
a two-character string containing `'\'` and `'t'`, whereas `"\t"` represents tab.

Sometimes you can use them interchangeably,

In [19]:
str1 = re.findall('\\t', "Please find \t")
print (str1)

str2 = re.findall(r'\\t', "Please find \\t")
print (str2)

['\t']
['\\t']

In [20]:
print('\\t')

\t

Sometimes not!

In [21]:
str3 = re.findall('\\\t', "Please find \t")
print (str3)
print('\\t')
print("Please find \\t")

['\t']
\t
Please find \t

In [22]:
r'\t'

'\\t'

In [23]:
s = 't\\t\tt'
print(s)

t\t	t

In [54]:
str1=re.match(r"\W(.)\1\W", " ff ")
print (str1)
print('---')
str2=re.match("\W(.)\1\W", " ff ")
print (str2)
print('---')
str3=re.match("\\W(.)\\1\\W", " ff ")
print (str3)

<re.Match object; span=(0, 4), match=' ff '>
---
None
---
<re.Match object; span=(0, 4), match=' ff '>

<>:4: SyntaxWarning: invalid escape sequence '\W'
<>:4: SyntaxWarning: invalid escape sequence '\W'
/var/folders/6s/bb6mgp0x50q3fjlqfsfpffjm0000gn/T/ipykernel_66849/4169345782.py:4: SyntaxWarning: invalid escape sequence '\W'
  str2=re.match("\W(.)\1\W", " ff ")

`"\W(.)\1\W"` doesn't match? What is the difference?

In [25]:
str4="\W(.)\1\W"
print (str4)
str4

\W(.)\W

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
/var/folders/6s/bb6mgp0x50q3fjlqfsfpffjm0000gn/T/ipykernel_66849/756452606.py:1: SyntaxWarning: invalid escape sequence '\W'
  str4="\W(.)\1\W"

'\\W(.)\x01\\W'

In [26]:
str4=r"\W(.)\1\W"
print (str4)
str4

\W(.)\1\W

'\\W(.)\\1\\W'

Now you might be able to guess, what `"\W(.)\1\W"` will match.

In [27]:
str2=re.match("\W(.)\1\W", " f\x01 ")
print (str2)

<re.Match object; span=(0, 4), match=' f\x01 '>

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
/var/folders/6s/bb6mgp0x50q3fjlqfsfpffjm0000gn/T/ipykernel_66849/2062020237.py:1: SyntaxWarning: invalid escape sequence '\W'
  str2=re.match("\W(.)\1\W", " f\x01 ")

It matches with non-word + any one character  + "\x01" + non-word.

**Note**: always fist validate your regular expression, then test with Python

\* is ??  <br>
\* is a wildcard similar with ? and +  <br>
\* matches 0+ <br>
? matches 0-1 <br>
\+ matches 1+ <br>

In [28]:
str1 = re.findall(r'.*', 'Please find all.')
print (str1)

['Please find all.', '']

In [29]:
str1 = re.findall(r'.?', 'Please find all.')
print (str1)

['P', 'l', 'e', 'a', 's', 'e', ' ', 'f', 'i', 'n', 'd', ' ', 'a', 'l', 'l', '.', '']

In [30]:
str1 = re.findall(r'.+', 'Please find all.')
print (str1)

['Please find all.']

In [31]:
str1 = re.findall(r'l+', 'Please find all')
print (str1)

['l', 'll']

## **2. Regular Expression for Dates**

Refine the regular expression for date to distinguish months with 29/30/31 days.

**Note**: assume all years are a leap year, which means every Feburary has 29 days.

In [32]:
# define a function to validate the input date
def date(pattern, m):
    if re.match(pattern, m):
        print (m + " is a date")
    else:
        print (m + " is NOT a date")

In [33]:
regex = r'''(?x)
    (?:
    # February (29 days every year)
      ([12][0-9]|0?[1-9])[/-](0?2)
    # 30-day months
      |(30|[12][0-9]|0?[1-9])[/-](0?[469]|11)
    # 31-day months
      |(3[01]|[12][0-9]|0?[1-9])[/-](0?[13578]|1[02])
    )
    # Year
    [/-]((?:[0-9]{2})?[0-9]{2})
'''

In [34]:
#date(r"((31[/-](0?[13578]|1[02]))|(30[/-](0?[469]|11))|(28[/-]02))[/-]((?:\d{2})?\d{2})", "28/02/2019")
date(regex, "28/02/2019")
date(regex, "31/04/2019")
date(regex, "29/05/2019")
date(regex, "31/06/2019")

28/02/2019 is a date
31/04/2019 is NOT a date
29/05/2019 is a date
31/06/2019 is NOT a date

We can draw the diagram to demon the logic of this regular expression:

![](https://drive.google.com/uc?export=download&id=1Wk7voq-u0iNBZ9wF-cBAjdvLowJoRaFJ)

## **3. Extract IPs, dates, and email address with regular expressions**

With following tasks we will use the mail box data ([mbox-short.txt](http://www.pythonlearn.com/code3/mbox-short.txt)) provided by the book [Python for Informatics: Exploring Information](http://www.pythonlearn.com/book.php#python-for-informatics).

In [35]:
# Colab please use this directory: '/content/drive/Shareddrives/FIT5196_S2_2025/week3/mbox-short.txt' as input directory
# If you are using a local environment, you can download the file from your shared drive and use the file path as input directory
infile = open('mbox-short.txt','r')

text = infile.read()

In [36]:
 text[:100]

'\\t\t\t\t\nFrom stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008\nReturn-Path: <postmaster@collab.sakai'

### **3.1 Find IP addresses**

We are trying to
1. find all IP addresses in the mbox-short dataset.
2. print unique IP addresses

In [37]:
str1 = re.findall(r'\b(?:\d{1,3}\.){3}\d{1,3}\b', "This is a IP address 111.23.39.99")
str1

['111.23.39.99']

![](https://drive.google.com/uc?export=download&id=1v5Os9EzlTo1sNwbMF9MTTMOZ0NpQVe9M)
From https://regexper.com/

In [38]:
str1= re.findall(r'(?:[0-9]{1,3}\.){3}[0-9]{1,3}', text)
if len(str1)>0:
    print (str1)

['141.211.14.90', '141.211.14.79', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.97', '141.211.93.149', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.25', '141.211.93.144', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.25', '141.211.14.43', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.46', '141.211.14.83', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.93', '141.211.93.142', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.46', '141.211.14.72', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.46', '141.211.93.151', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.25', '141.211.14.79', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.36', '141.211.14.84', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.97', '141.211.93.152', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.39', '141.211.14.79', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.90', '141.211.93.153', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.97', '141.211.14.84', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.25', '141.211.14.79', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.90', '141.211.14.76', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.39', '141.211.14.76', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.98', '141.211.14.83', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.92', '141.211.93.145', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.46', '141.211.93.143', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.25', '141.211.14.58', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.91', '141.211.93.142', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.91', '141.211.14.58', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.39', '141.211.93.141', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.34', '141.211.93.149', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.46', '141.211.93.145', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200', '141.211.14.91', '141.211.14.58', '194.35.219.184', '127.0.0.1', '194.35.219.182', '134.68.220.122', '127.0.0.1', '8.12.11.200', '8.12.11.200']

By running the code above, we are able to print all IP addresses.

Next can we save all unique IP address in a list? We will need to read the whole txt file in to `text`, and then apply `re.findall` function. `set()` function returns the unique values.

In [39]:
str1=re.findall(r'(?:[0-9]{1,3}\.){3}[0-9]{1,3}', text)
set(str1)

{'127.0.0.1',
 '134.68.220.122',
 '141.211.14.25',
 '141.211.14.34',
 '141.211.14.36',
 '141.211.14.39',
 '141.211.14.43',
 '141.211.14.46',
 '141.211.14.58',
 '141.211.14.72',
 '141.211.14.76',
 '141.211.14.79',
 '141.211.14.83',
 '141.211.14.84',
 '141.211.14.90',
 '141.211.14.91',
 '141.211.14.92',
 '141.211.14.93',
 '141.211.14.97',
 '141.211.14.98',
 '141.211.93.141',
 '141.211.93.142',
 '141.211.93.143',
 '141.211.93.144',
 '141.211.93.145',
 '141.211.93.149',
 '141.211.93.151',
 '141.211.93.152',
 '141.211.93.153',
 '194.35.219.182',
 '194.35.219.184',
 '8.12.11.200'}

### **3.2 Extract All date time**


In the next task, we need to extract all date time from the file. We trust that all date time are valid for now.

In [40]:
str1=re.findall(r'(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})', text)
set(str1)

{'2007-09-12 16:17:59',
 '2007-12-12 21:40:33',
 '2007-12-17 17:11:08',
 '2007-12-20 15:25:38',
 '2007-12-20 21:26:28',
 '2007-12-28 23:44:24',
 '2008-01-03 16:22:14',
 '2008-01-03 16:27:29',
 '2008-01-03 16:33:02',
 '2008-01-03 17:05:11',
 '2008-01-03 17:16:39',
 '2008-01-03 19:23:46',
 '2008-01-04 04:05:43',
 '2008-01-04 04:31:35',
 '2008-01-04 04:47:16',
 '2008-01-04 06:05:51',
 '2008-01-04 07:00:10',
 '2008-01-04 09:02:54',
 '2008-01-04 10:01:40',
 '2008-01-04 10:15:54',
 '2008-01-04 10:37:04',
 '2008-01-04 11:08:38',
 '2008-01-04 11:09:12',
 '2008-01-04 11:10:04',
 '2008-01-04 11:11:00',
 '2008-01-04 11:33:05',
 '2008-01-04 11:35:25',
 '2008-01-04 13:05:51',
 '2008-01-04 14:48:37',
 '2008-01-04 15:01:37',
 '2008-01-04 15:44:39',
 '2008-01-04 16:09:01',
 '2008-01-04 18:08:50',
 '2008-01-05 09:12:07'}

### **3.3 Extract author's email address**


There are many email addresses included in the file. We would like to extract email addresses from the Author the format is normally:

`"Author: stephen.marquard@uct.ac.za"`

Now lets see if we can use the following regular expression:

```python
r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+"
```
which was copied and pasted from http://emailregex.com/

Does it work in the task?

In [41]:
str1=re.findall(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+", text)
set(str1)

{'200801032122.m03LMFo4005148@nakamura.uits.iupui.edu',
 '200801032127.m03LRUqH005177@nakamura.uits.iupui.edu',
 '200801032133.m03LX3gG005191@nakamura.uits.iupui.edu',
 '200801032205.m03M5Ea7005273@nakamura.uits.iupui.edu',
 '200801032216.m03MGhDa005292@nakamura.uits.iupui.edu',
 '200801040023.m040NpCc005473@nakamura.uits.iupui.edu',
 '200801040905.m0495rWB006420@nakamura.uits.iupui.edu',
 '200801040932.m049W2i5006493@nakamura.uits.iupui.edu',
 '200801040947.m049lUxo006517@nakamura.uits.iupui.edu',
 '200801041106.m04B6lK3006677@nakamura.uits.iupui.edu',
 '200801041200.m04C0gfK006793@nakamura.uits.iupui.edu',
 '200801041403.m04E3psW006926@nakamura.uits.iupui.edu',
 '200801041502.m04F21Jo007031@nakamura.uits.iupui.edu',
 '200801041515.m04FFv42007050@nakamura.uits.iupui.edu',
 '200801041537.m04Fb6Ci007092@nakamura.uits.iupui.edu',
 '200801041608.m04G8d7w007184@nakamura.uits.iupui.edu',
 '200801041609.m04G9EuX007197@nakamura.uits.iupui.edu',
 '200801041610.m04GA5KP007209@nakamura.uits.iupui.edu',
 '200801041611.m04GB1Lb007221@nakamura.uits.iupui.edu',
 '200801041633.m04GX6eG007292@nakamura.uits.iupui.edu',
 '200801041635.m04GZQGZ007313@nakamura.uits.iupui.edu',
 '200801041948.m04JmdwO007705@nakamura.uits.iupui.edu',
 '200801042001.m04K1cO0007738@nakamura.uits.iupui.edu',
 '200801042044.m04Kiem3007881@nakamura.uits.iupui.edu',
 '200801042109.m04L92hb007923@nakamura.uits.iupui.edu',
 '200801042308.m04N8v6O008125@nakamura.uits.iupui.edu',
 '200801051412.m05ECIaH010327@nakamura.uits.iupui.edu',
 'antranig@caret.cam.ac.uk',
 'cwen@iupui.edu',
 'david.horwitz@uct.ac.za',
 'gopal.ramasammycook@gmail.com',
 'gsilver@umich.edu',
 'hu2@iupui.edu',
 'josrodri@iupui.edu',
 'louis@media.berkeley.edu',
 'postmaster@collab.sakaiproject.org',
 'ray@media.berkeley.edu',
 'rjlowe@iupui.edu',
 'source@collab.sakaiproject.org',
 'stephen.marquard@uct.ac.za',
 'wagnermr@iupui.edu',
 'zqian@umich.edu'}

What if I only want email address after Author ?

In [42]:
str1=re.findall(r'Author: ([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)', text)
str1

['stephen.marquard@uct.ac.za',
 'louis@media.berkeley.edu',
 'zqian@umich.edu',
 'rjlowe@iupui.edu',
 'zqian@umich.edu',
 'rjlowe@iupui.edu',
 'cwen@iupui.edu',
 'cwen@iupui.edu',
 'gsilver@umich.edu',
 'gsilver@umich.edu',
 'zqian@umich.edu',
 'gsilver@umich.edu',
 'wagnermr@iupui.edu',
 'zqian@umich.edu',
 'antranig@caret.cam.ac.uk',
 'gopal.ramasammycook@gmail.com',
 'david.horwitz@uct.ac.za',
 'david.horwitz@uct.ac.za',
 'david.horwitz@uct.ac.za',
 'david.horwitz@uct.ac.za',
 'stephen.marquard@uct.ac.za',
 'louis@media.berkeley.edu',
 'louis@media.berkeley.edu',
 'ray@media.berkeley.edu',
 'cwen@iupui.edu',
 'cwen@iupui.edu',
 'cwen@iupui.edu']

## **Task: Read and load raw data**

Last week, we load an `Air Crashes` data in Task 2. The csv file has been already preprocessed in a structured format. However, most of time, we need to work directly on the raw data.

In this task, you will load the raw data file for `Air Crashes` and use regular expressions to convert it into the appropriate structure.

In [55]:
# Colab please use the following directory in codes below
# If you are using a local environment, you can download the file from your shared drive and use the file path as input directory

# load data in target structure
aircrash = pd.read_csv('AirCrashes.csv')
aircrash.head()

,Flight,Mode,Casualties,Circumstances,Country,Crew,Date,Ground,Latitude,Location,Longitude,Notes,Passengers,Phase,Reason,Total Dead,Type
0,Aeroflot Flight 217,Ilyushin Il-62,Extremely High,Bad Visibility by Day,Russia,10,13/10/1972,0,55.755826,Moscow - Russia,37.617300,No survivors,164,APR,Accident,174,COM
1,Aeroflot Flight 3352,Tupolev Tu-154,Extremely High,Bad Visibility by Night,Russia,5,11/10/1984,4,54.966667,Omsk - Russia,73.383333,Some survivors,169,LDG,Accident,178,COM
2,Aeroflot Flight 4227,Tupolev Tu-154B-2,Extremely High,Bad Visibility by Night,Kazakhstan,10,1890-07-08,0,43.255058,Almaty - Kazakhstan,76.912628,No survivors,156,ENR,Accident,166,COM
3,Aeroflot Flight 7425,NaN,Extremely High,Bad Visibility by Night,NaN,9,10/7/1985,0,42.156667,Uchkuduk - Uzbekistan,63.555556,No survivors,191,ENR,Accident,0,COM
4,Aeroflot/Moldovia (CCCP-65816),Tupolev Tu-134A(both),Extremely High,Bad Visibility by Night,Kazakhstan,13,11/8/1979,0,48.812500,NaN,46.763611,No survivors,165,ENR,Accident,178,COM

Above is the final structure we would like to have.

Now, let's open the raw file.

In [56]:
# load raw data
df = pd.read_csv('AirCrashes_raw.csv')
df.shape

(927, 1)

In [57]:
df.head(30)

                                                   Incident American Airlines Flight 11 involving a Boeing 767-223ER in 2001
Casualties                                                                             Extremely High
Total Dead                                                                                       1692
Crew                                                                                               11
Passengers                                                                                         81
Ground                                                                                           1600
Notes                                                                                    No survivors
Type                                                                                              INH
Reason                                                                                         Attack
Location                                                                     New York - New York - US
Country                                                                                            US
Phase                                                                                             ENR
Date                                                                                       2001-09-11
Latitude                                                                                   40.7143528
Longitude                                                                                 -74.0059731
Circumstances                                                                  Good Visibility by Day
Incident United Airlines Flight 175 involving a...                                                NaN
Casualties                                                                             Extremely High
Total Dead                                                                                        965
Crew                                                                                                9
Passengers                                                                                         56
Ground                                                                                            900
Notes                                                                                    No survivors
Type                                                                                              INH
Reason                                                                                         Attack
Location                                                                     New York - New York - US
Country                                                                                           USA
Phase                                                                                             ENR
Date                                                                                       2001-09-11
Latitude                                                                                   40.7143528
Longitude                                                                                 -74.0059731

### Parse raw Air Crashes data with regular expressions

We'll now convert the unstructured `AirCrashes_raw.csv` (really a line-oriented text file) into a structured DataFrame.

Parsing logic:
1. Detect header lines starting with `Incident` to start a new record.
2. Extract Flight (flight identifiers part), Mode (aircraft type(s)), and Year from the header using regex.
3. Subsequent non-empty lines are `Label,Value` pairs. Some values may be empty (e.g. `Crew,`).
4. Blank line or a new `Incident` line finalises the current record.
5. Post-process: clean numeric fields, validate dates, flag suspicious years or malformed dates.

We'll build a parser function so you can reuse / adapt it. After parsing we'll get a DataFrame similar to the previously provided structured `AirCrashes.csv`. Next cell implements this.

In [58]:
# 步骤1：按纯文本逐行读取原始文件（而不是直接让 pandas 解析成一列）
# 这样可以精细控制“事件头行（Incident ...）”与“字段行（Label,Value）”以及空行的识别。
from pathlib import Path  # Path 对象便于处理文件路径
raw_path = Path('AirCrashes_raw.csv')  # 指向原始数据文件
raw_text = raw_path.read_text(encoding='utf-8')  # 读取整个文件为一个长字符串
lines = raw_text.splitlines()  # 分割成行列表（保留顺序）
print(f'Total lines (including blanks): {len(lines)}')  # 打印总行数，包含空行用于调试
print('First 8 lines:')
for l in lines[:8]:  # 预览前 8 行，确认格式：第一行为 Incident 开头，之后是若干 “字段,值” 行
    print(l)

Total lines (including blanks): 986
First 8 lines:

Incident American Airlines Flight 11 involving a Boeing 767-223ER in 2001
Casualties,Extremely High
Total Dead,1692
Crew,11
Passengers,81
Ground,1600
Notes,No survivors

#### Step 2: Identify incident header lines
We first locate lines that begin a new incident. Pattern to capture:
`Incident <description> in <year>`
We'll test the regex against a sample of lines.

In [59]:
import re  # 导入正则表达式库
# incident_re 用于捕获“事件头行”中间部分(航班/飞机描述)与年份
# ^Incident\s+ : 行首以 Incident 开始，后跟一个或多个空白
# (.+?)         : 非贪婪匹配中间描述（航班 + 'involving' + 机型等）
# \s+in\s+     : 关键字 in，两侧若干空白
# (\d{4})$     : 4 位年份，行尾结束
incident_re = re.compile(r'^Incident\s+(.+?)\s+in\s+(\d{4})$')
# 采样部分以 Incident 开头的行做测试
header_candidates = [l for l in lines if l.startswith('Incident')][:5]
for hc in header_candidates:
    m = incident_re.match(hc)
    # 验证匹配是否成功，并输出捕获到的组（中间描述, 年份）
    print(hc, '->', 'MATCH' if m else 'NO MATCH', m.groups() if m else '')

Incident American Airlines Flight 11 involving a Boeing 767-223ER in 2001 -> MATCH ('American Airlines Flight 11 involving a Boeing 767-223ER', '2001')
Incident United Airlines Flight 175 involving a Boeing 767-222 in 2001 -> MATCH ('United Airlines Flight 175 involving a Boeing 767-222', '2001')
Incident Pan Am Flight 1736 and KLM Flight 4805 involving a Boeing 747-121 and Boeing 747-206B in 1977 -> MATCH ('Pan Am Flight 1736 and KLM Flight 4805 involving a Boeing 747-121 and\xa0Boeing 747-206B', '1977')
Incident Japan Airlines Flight 123 involving a Beoing 747SR-46 in 1985 -> MATCH ('Japan Airlines Flight 123 involving a Beoing 747SR-46', '1985')
Incident Saudi Arabian Flight 763 and involving a Boeing 747-168B and Ilyushin Il-76TD in 1996 -> MATCH ('Saudi Arabian Flight 763 and involving a Boeing 747-168B and\xa0Ilyushin Il-76TD', '1996')

#### Step 3: Split header into `Flight` and `Mode`
We now take the portion between `Incident` and the year, and split around the keyword `involving` to separate the flight identifiers from aircraft type(s).

In [60]:
# header_split_re: 再次匹配“Incident ... in 年”，便于拆出中段描述与年份
header_split_re = re.compile(r'^Incident\s+(?P<mid>.+?)\s+in\s+(?P<Year>\d{4})$')
# flight_mode_re: 将中段描述再按关键字 involving 拆分为 Flight 与 Mode
# ^(?P<Flight>.+?)\s+involving\s+(?P<Mode>.+)$
#  - (?P<Flight>.+?) 非贪婪匹配航班部分（可能含多个航班）
#  - involving 关键字
#  - (?P<Mode>.+)   剩余全部作为机型/型号描述
flight_mode_re = re.compile(r'^(?P<Flight>.+?)\s+involving\s+(?P<Mode>.+)$', re.IGNORECASE)

examples = [l for l in lines if l.startswith('Incident')][:3]
for ex in examples:
    m = header_split_re.match(ex)
    if m:
        mid = m.group('mid')  # 中间部分（含 Flight + involving + Mode）
        year = m.group('Year')
        # 为复用 flight_mode_re，将 mid 前面补一个单词 Incident，便于模式统一
        fm = flight_mode_re.match('Incident ' + mid)
        if fm:
            # 去掉前置 Incident，strip 清理多余空格
            flight = fm.group('Flight').replace('Incident','').strip()
            mode = fm.group('Mode').strip()
        else:
            # 如果没有 involving，就把整个 mid 当做 Flight
            flight, mode = mid, None
        print(f'Original: {ex}\n  Flight: {flight}\n  Mode: {mode}\n  Year: {year}')

Original: Incident American Airlines Flight 11 involving a Boeing 767-223ER in 2001
  Flight: American Airlines Flight 11
  Mode: a Boeing 767-223ER
  Year: 2001
Original: Incident United Airlines Flight 175 involving a Boeing 767-222 in 2001
  Flight: United Airlines Flight 175
  Mode: a Boeing 767-222
  Year: 2001
Original: Incident Pan Am Flight 1736 and KLM Flight 4805 involving a Boeing 747-121 and Boeing 747-206B in 1977
  Flight: Pan Am Flight 1736 and KLM Flight 4805
  Mode: a Boeing 747-121 and Boeing 747-206B
  Year: 1977

#### Step 4: Parse label,value lines
Each subsequent non-empty line (until a blank) has the form `Label,Value`. We test a regex and handle empty values (e.g., `Crew,`).


## 1. 什么是捕获组
在正则表达式里，用小括号 `(...)` 括起来的部分叫 **捕获组**。  
它的作用是：
- 把匹配结果的一部分“捕获”下来，以便后续提取或复用。  
- 捕获组默认用编号表示，编号从 1 开始（组 0 是整个正则）。  

例子：
```python
import re
m = re.match(r'(\d{4})-(\d{2})-(\d{2})', "2025-08-17")
print(m.group(1))  # 2025
print(m.group(2))  # 08
print(m.group(3))  # 17
```

---

## 2. 命名捕获组
**语法**：
```
(?P<name>pattern)
```
- `name` 是组的名字（必须是合法的标识符：字母/数字/下划线，不能以数字开头）。  
- `pattern` 是要匹配的内容。  

这样你就可以用名字而不是数字来访问结果，更清晰。  

例子：
```python
import re
m = re.match(r'(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})', "2025-08-17")

print(m.group("year"))   # 2025
print(m.group("month"))  # 08
print(m.group("day"))    # 17

print(m.groupdict())     # {'year': '2025', 'month': '08', 'day': '17'}
```

In [61]:
# label_value_re 捕获形如 Label,Value 的行
# (?P<label>[^,]+?) : 逗号前的字段名（非逗号最短匹配）
# ,
# (?P<value>.*)     : 逗号后的全部内容（可以为空字符串）
label_value_re = re.compile(r'^(?P<label>[^,]+?),(?P<value>.*)$')
# 在首个 Incident 后收集若干字段行作为示例
sample_label_lines = []
collect = False
for l in lines:
    if l.startswith('Incident'):
        collect = True
        continue
    if collect:
        if not l.strip():  # 空行则结束示例采样
            break
        if ',' in l:
            sample_label_lines.append(l)
    if len(sample_label_lines) >= 10:
        break
for sl in sample_label_lines:
    m = label_value_re.match(sl)
    print(sl, '->', m.group('label'), '|', m.group('value'))

Casualties,Extremely High -> Casualties | Extremely High
Total Dead,1692 -> Total Dead | 1692
Crew,11 -> Crew | 11
Passengers,81 -> Passengers | 81
Ground,1600 -> Ground | 1600
Notes,No survivors -> Notes | No survivors
Type,INH -> Type | INH
Reason,Attack -> Reason | Attack
Location,New York - New York - US -> Location | New York - New York - US
Country,US -> Country | US

#### Step 5: Assemble records
Iterate through lines, start a new dict on each header, accumulate label/value pairs, flush on blank line. We'll print the first parsed record for inspection.

In [62]:
# 迭代所有行并组装成 records 列表；每条记录是一个字典
records = []  # 存放所有事故记录
current = {}  # 当前正在填充的记录

for line in lines + ['']:  # 结尾额外加一个空字符串，确保最后一条能被 flush
    line = line.strip('\ufeff').rstrip()  # 去除 BOM 和末尾空白
    if not line:  # 空行表示一个事件块结束
        if current.get('Flight') or current.get('Year'):
            records.append(current)
            current = {}
        continue
    mh = incident_re.match(line)
    if mh:  # 事件头行，开始新记录
        if current.get('Flight') or current.get('Year'):
            records.append(current)
            current = {}
        header_mid, year = mh.groups()
        fm = flight_mode_re.match('Incident ' + header_mid)
        if fm:  # 成功分离 Flight 与 Mode
            current['Flight'] = fm.group('Flight').replace('Incident','').strip()
            current['Mode'] = fm.group('Mode').strip()
        else:
            current['Flight'] = header_mid
        current['Year'] = int(year)  # 年份转为整数
        continue
    mv = label_value_re.match(line)  # 普通字段行
    if mv:
        lab, val = mv.group('label').strip(), mv.group('value').strip() or None
        current[lab] = val  # 若值为空串则存 None

print('Total records parsed (raw, before cleaning):', len(records))
print('First record keys:', list(records[0].keys()))
print('First record sample:', records[0])

Total records parsed (raw, before cleaning): 58
First record keys: ['Flight', 'Mode', 'Year', 'Casualties', 'Total Dead', 'Crew', 'Passengers', 'Ground', 'Notes', 'Type', 'Reason', 'Location', 'Country', 'Phase', 'Date', 'Latitude', 'Longitude', 'Circumstances']
First record sample: {'Flight': 'American Airlines Flight 11', 'Mode': 'a Boeing 767-223ER', 'Year': 2001, 'Casualties': 'Extremely High', 'Total Dead': '1692', 'Crew': '11', 'Passengers': '81', 'Ground': '1600', 'Notes': 'No survivors', 'Type': 'INH', 'Reason': 'Attack', 'Location': 'New York - New York - US', 'Country': 'US', 'Phase': 'ENR', 'Date': '2001-09-11', 'Latitude': '40.7143528', 'Longitude': '-74.0059731', 'Circumstances': 'Good Visibility by Day'}

#### Step 6: Create DataFrame and clean
Rename columns, convert numeric fields, validate date format, attempt minor date fix for obvious month/day swaps.

In [63]:
import pandas as pd  # 数据框处理
parsed_df = pd.DataFrame(records)  # 将列表字典转为 DataFrame
print('Shape before cleaning:', parsed_df.shape)  # 查看初始维度

# 重命名列：Total Dead -> Total_Dead 便于无空格字段名
parsed_df = parsed_df.rename(columns={'Total Dead':'Total_Dead'})

# 数值列转换：提取可能混杂的纯数字（这里简单使用首个整数匹配）
for col in ['Total_Dead','Crew','Passengers','Ground','Year']:
    if col in parsed_df.columns:
        parsed_df[col] = (parsed_df[col].astype(str)
                           .str.extract(r'(-?\d+)', expand=False)  # 提取数字部分
                           .astype('Int64'))  # 使用 pandas 可空整型 Int64

# 经纬度列转为浮点，非法值 -> NaN
for col in ['Latitude','Longitude']:
    if col in parsed_df.columns:
        parsed_df[col] = pd.to_numeric(parsed_df[col], errors='coerce')

# 日期合法性初步校验 + 简单“月日调换”修正（当月>12 且日<=12 时交换）
import re as _re
fix_pattern = _re.compile(r'^(\d{4})-(\d{2})-(\d{2})$')

def fix_date(d):
    if pd.isna(d):
        return d
    m = fix_pattern.match(d)
    if not m:
        return d
    y, mth, day = m.groups()
    if int(mth) > 12 and int(day) <= 12:  # 识别明显调换
        return f"{y}-{day.zfill(2)}-{mth.zfill(2)}"
    return d

parsed_df['Date'] = parsed_df['Date'].apply(fix_date)
parsed_df['Date_valid'] = parsed_df['Date'].str.match(r'^\d{4}-\d{2}-\d{2}$')
print('Invalid dates count:', (~parsed_df['Date_valid']).sum())

parsed_df.head()

Shape before cleaning: (58, 18)
Invalid dates count: 0

,Flight,Mode,Year,Casualties,Total_Dead,Crew,Passengers,Ground,Notes,Type,Reason,Location,Country,Phase,Date,Latitude,Longitude,Circumstances,Date_valid
0,American Airlines Flight 11,a Boeing 767-223ER,2001,Extremely High,1692,11,81,1600,No survivors,INH,Attack,New York - New York - US,US,ENR,2001-09-11,40.714353,-74.005973,Good Visibility by Day,True
1,United Airlines Flight 175,a Boeing 767-222,2001,Extremely High,965,9,56,900,No survivors,INH,Attack,New York - New York - US,USA,ENR,2001-09-11,40.714353,-74.005973,Good Visibility by Day,True
2,Pan Am Flight 1736 and KLM Flight 4805,a Boeing 747-121 and Boeing 747-206B,1977,Extremely High,583,23,560,0,Some survivors,COM,Accident,Tenerife - Spain,Spain,TOF,1977-03-27,28.291564,-16.629130,Bad Visibility by Day,True
3,Japan Airlines Flight 123,a Beoing 747SR-46,1985,Extremely High,520,15,505,0,Some survivors,COM,Accident,Ueno - Japan,Japan,ENR,1985-08-12,35.708946,139.774268,Bad Visibility by Night,True
4,Saudi Arabian Flight 763 and,a Boeing 747-168B and Ilyushin Il-76TD,1996,Extremely High,349,33,316,0,No survivors,NaN,Accident,Charkhi Dadri - India,India,ENR,1996-11-12,28.600000,76.266700,Bad Visibility by Night,True

#### Step 7: Reorder columns & (optionally) compare
Arrange columns to align with target structure and briefly compare with the preprocessed `aircrash` DataFrame if loaded earlier.

In [64]:
# 设定期望列顺序（尽量与已有结构化 csv 对齐）
preferred_order = ['Flight','Mode','Casualties','Circumstances','Country','Crew','Date','Ground','Latitude','Location','Longitude','Notes','Passengers','Phase','Reason','Total_Dead','Type','Year']
# 先放置存在于 parsed_df 中且在 preferred_order 里的列，再追加剩余列
ordered_cols = [c for c in preferred_order if c in parsed_df.columns] + [c for c in parsed_df.columns if c not in preferred_order]
final_df = parsed_df[ordered_cols]
print('Final shape:', final_df.shape)

# 如果之前加载过结构化的 aircrash DataFrame，可做简单比较
if 'aircrash' in globals():
    print('Existing structured shape:', aircrash.shape)
    print('Columns missing vs target:', set(aircrash.columns) - set(final_df.columns))

final_df.head(10)

Final shape: (58, 19)
Existing structured shape: (58, 17)
Columns missing vs target: {'Total Dead'}

,Flight,Mode,Casualties,Circumstances,Country,Crew,Date,Ground,Latitude,Location,Longitude,Notes,Passengers,Phase,Reason,Total_Dead,Type,Year,Date_valid
0,American Airlines Flight 11,a Boeing 767-223ER,Extremely High,Good Visibility by Day,US,11,2001-09-11,1600,40.714353,New York - New York - US,-74.005973,No survivors,81,ENR,Attack,1692,INH,2001,True
1,United Airlines Flight 175,a Boeing 767-222,Extremely High,Good Visibility by Day,USA,9,2001-09-11,900,40.714353,New York - New York - US,-74.005973,No survivors,56,ENR,Attack,965,INH,2001,True
2,Pan Am Flight 1736 and KLM Flight 4805,a Boeing 747-121 and Boeing 747-206B,Extremely High,Bad Visibility by Day,Spain,23,1977-03-27,0,28.291564,Tenerife - Spain,-16.629130,Some survivors,560,TOF,Accident,583,COM,1977,True
3,Japan Airlines Flight 123,a Beoing 747SR-46,Extremely High,Bad Visibility by Night,Japan,15,1985-08-12,0,35.708946,Ueno - Japan,139.774268,Some survivors,505,ENR,Accident,520,COM,1985,True
4,Saudi Arabian Flight 763 and,a Boeing 747-168B and Ilyushin Il-76TD,Extremely High,Bad Visibility by Night,India,33,1996-11-12,0,28.600000,Charkhi Dadri - India,76.266700,No survivors,316,ENR,Accident,349,NaN,1996,True
5,Turkish Airlines Flight 981,a McDonnell Douglas DC-10-10,Extremely High,Bad Visibility by Night,France,11,1974-03-03,0,49.171795,Fontaine-Chaalis - France,2.684157,No survivors,335,ENR,Accident,346,COM,1974,True
6,Air India Flight 182,a Boeing 747-237B,Extremely High,Bad Visibility by Night,Ireland,22,1985-06-23,0,51.896892,Atlantic Ocean - Cork - Ireland,-8.486316,No survivors,307,ENR,Attack,329,INB,1985,True
7,Saudia Flight 163,a Lockheed L-1011-200 TriStar,Extremely High,Bad Visibility by Night,Saudi Arabia,14,1980-08-19,0,24.711667,Riyadh - Saudi Arabia,46.724167,No survivors,287,ENR,Accident,301,COM,1980,True
8,Iran Air Flight 655,a Airbus A300B2-203,Extremely High,Bad Visibility by Night,Iran,16,1988-07-03,0,26.594475,Strait of Hormuz - Iran,56.471993,No survivors,274,ENR,Attack,290,EXG,1988,True
9,Iranian Air Force (15-2280),a Ilyushin Il-76MD,Extremely High,Bad Visibility by Night,Iran,18,2003-02-19,0,30.280270,Kerman - Iran,57.067020,No survivors,257,ENR,Accident,275,MIL,2003,True

#### Step 8: Summary & Next Improvements / 总结与可改进点
**思路回顾 (Mindset Recap)**:
- 分阶段：检测头行 (headers) -> 提取字段 (fields) -> 组装记录 (records) -> 清洗 (cleaning) -> 验证 (validation)。
- 每一步先用少量样本测试正则，降低后续大规模错误风险。
- 保留中间输出（行数、示例、字段列表、形状）方便调试与溯源。
- 数据清洗采用最小侵入：仅做必要重命名 / 类型转换 / 简单日期修正。